#ifndef TYPEFONCTION_H_INCLUDED
#define TYPEFONCTION_H_INCLUDED

enum TYPEFUNCTION{
    SPHEREFUNCTION,
    RASTRIGINFUNCTION,
    ROSENBROCKFUNCTION,
    GRIEWANKFUNCTION
};

#endif // TYPEFONCTION_H_INCLUDED
